name = "fps"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"
fluo = { git = "https://github.com/nablaFox/Fluo", ref = "main" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
